### ISSUE TITLE
I am open to adding things for MEP

### ISSUE THREAD

**Issue by arif-hanif** [design-technology/OpenAEC#1]
Do you have any specific plans for this?

**Comment by ksobon** [comment]
Well the plan is to pull together your favourite utilities so that others also have access to them but most importantly so that you don't always have to maintain them. If there is a group of people managing these, I am sure we will all collectively spend less time managing these tools. 

If you want to contribute, just fork the repo, and create a pull request. I just started this, so I am still working on the documentation, but I will better know what needs to be documented if you have trouble submitting a PR or building these tools. 

Cheers, and thank you for your contributions!

**Comment by arif-hanif** [comment]
I agree with you on all fronts, I will definitely get involved,
